//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsitePorfolio.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebsitePorfolio.Resources.HomeTexts", typeof(HomeTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi! My name is Tomek and I live in Poland. I am currently studing at post-diploma studies focused on .NET technologies and programming using C# in which I am excceptionally interested. I have a Master degree in Mechanical Engineering and Bachelor degree in PowerEngineering. I have spent one year in Portugal as Erasmus+ student, studying Sustainable Energies. I love to travel and I had two bigger journeys by hitchiking (from Poland to Greece and Italy). Also my hobbies are solving programming riddles, surfin [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutMeContent {
            get {
                return ResourceManager.GetString("AboutMeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About me.
        /// </summary>
        public static string AboutMeTitle {
            get {
                return ResourceManager.GetString("AboutMeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bialystok, Poland.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string ContactTitle {
            get {
                return ResourceManager.GetString("ContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICT technology and programming.
        /// </summary>
        public static string EducationField1 {
            get {
                return ResourceManager.GetString("EducationField1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sustainable Energies.
        /// </summary>
        public static string EducationField2 {
            get {
                return ResourceManager.GetString("EducationField2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Degree in Mechanical Engineering.
        /// </summary>
        public static string EducationField3 {
            get {
                return ResourceManager.GetString("EducationField3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bachelor Degree in Power Engineering.
        /// </summary>
        public static string EducationField4 {
            get {
                return ResourceManager.GetString("EducationField4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string EducationTitle {
            get {
                return ResourceManager.GetString("EducationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working experience.
        /// </summary>
        public static string ExperienceTitle {
            get {
                return ResourceManager.GetString("ExperienceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi, I am Tomek.
        /// </summary>
        public static string Intro {
            get {
                return ResourceManager.GetString("Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wm Morrison Supermarkets plc.
        /// </summary>
        public static string Job1 {
            get {
                return ResourceManager.GetString("Job1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enea S.A. Production.
        /// </summary>
        public static string Job2 {
            get {
                return ResourceManager.GetString("Job2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summer job in England..
        /// </summary>
        public static string JobDescription1 {
            get {
                return ResourceManager.GetString("JobDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internship at power plant in Bialystok city..
        /// </summary>
        public static string JobDescription2 {
            get {
                return ResourceManager.GetString("JobDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehousing.
        /// </summary>
        public static string JobPosition1 {
            get {
                return ResourceManager.GetString("JobPosition1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internship.
        /// </summary>
        public static string JobPosition2 {
            get {
                return ResourceManager.GetString("JobPosition2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2015 June - 2015 September.
        /// </summary>
        public static string JobYear1 {
            get {
                return ResourceManager.GetString("JobYear1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2014 July - 2014 August.
        /// </summary>
        public static string JobYear2 {
            get {
                return ResourceManager.GetString("JobYear2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish (Native).
        /// </summary>
        public static string Language1 {
            get {
                return ResourceManager.GetString("Language1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (B2 according to CEFR).
        /// </summary>
        public static string Language2 {
            get {
                return ResourceManager.GetString("Language2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greek (Beginner).
        /// </summary>
        public static string Language3 {
            get {
                return ResourceManager.GetString("Language3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string LanguagesTitle {
            get {
                return ResourceManager.GetString("LanguagesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bialystok University of Technology.
        /// </summary>
        public static string School1 {
            get {
                return ResourceManager.GetString("School1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instituto Superior de Engenharia do Porto.
        /// </summary>
        public static string School2 {
            get {
                return ResourceManager.GetString("School2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bialystok University of Technology.
        /// </summary>
        public static string School3 {
            get {
                return ResourceManager.GetString("School3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bialystok University of Technology.
        /// </summary>
        public static string School4 {
            get {
                return ResourceManager.GetString("School4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post diploma studies about programming in C# language using .Net technologies. Including basic concepts of IT..
        /// </summary>
        public static string SchoolDescription1 {
            get {
                return ResourceManager.GetString("SchoolDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participation in student exchange programme &quot;Erasmus+&quot; in Portugal for one year..
        /// </summary>
        public static string SchoolDescription2 {
            get {
                return ResourceManager.GetString("SchoolDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialization in Technology of heating, refrigeration and air conditioning finished with mark 4.5 (B). Thesis susbject &quot;Computer-aided analysis of heat exchange processes on finned surfaces.&quot; using SolidWorks Software..
        /// </summary>
        public static string SchoolDescription3 {
            get {
                return ResourceManager.GetString("SchoolDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialization in energy transfer and production finished with mark 4 (C). Thesis susbject &quot;Project of ground heat exchanger&quot; using SolidWorks Software..
        /// </summary>
        public static string SchoolDescription4 {
            get {
                return ResourceManager.GetString("SchoolDescription4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2017 October - 2018 June.
        /// </summary>
        public static string SchoolYears1 {
            get {
                return ResourceManager.GetString("SchoolYears1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2016 September - 2017 July.
        /// </summary>
        public static string SchoolYears2 {
            get {
                return ResourceManager.GetString("SchoolYears2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2016 February - 2018 November.
        /// </summary>
        public static string SchoolYears3 {
            get {
                return ResourceManager.GetString("SchoolYears3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2011 September - 2015 March.
        /// </summary>
        public static string SchoolYears4 {
            get {
                return ResourceManager.GetString("SchoolYears4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C# programming language.
        /// </summary>
        public static string SkillsContent1 {
            get {
                return ResourceManager.GetString("SkillsContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solidworks (+flow simulation).
        /// </summary>
        public static string SkillsContent2 {
            get {
                return ResourceManager.GetString("SkillsContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows, ms office.
        /// </summary>
        public static string SkillsContent3 {
            get {
                return ResourceManager.GetString("SkillsContent3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic knowledge in .Net Framework (WPF, MVC), Oracle Database SQL, Linux, Html, XML, XAML.
        /// </summary>
        public static string SkillsContent4 {
            get {
                return ResourceManager.GetString("SkillsContent4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Familiarity with Git, GitHub, Unity Engine, Android Studio, Android, Photoshop, Sony Vegas Pro, Catia.
        /// </summary>
        public static string SkillsContent5 {
            get {
                return ResourceManager.GetString("SkillsContent5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string SkillsTitle {
            get {
                return ResourceManager.GetString("SkillsTitle", resourceCulture);
            }
        }
    }
}
